env = "test" # "test", "dev", "prod"

[log]
# Log level: "trace", "debug", "info", "warn", "error"
level = "info"

[server]
# The address to bind to.
addr = ":8080"
# The maximum number of seconds to wait for graceful shutdown.
graceful_shutdown = 10

[base]
userbase = "http://127.0.0.1:8080"
logbase = "http://127.0.0.1:8080"
walletbase = "http://127.0.0.1:8080"
